# Generated by Django 3.2.9 on 2023-03-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caadapprovalhistory',
            name='bha_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caadapprovalhistory',
            name='action_status',
            field=models.CharField(choices=[('RH APPROVED', 'RH APPROVED'), ('OC APPROVED', 'OC APPROVED'), ('HCS APPROVED', 'HCS APPROVED'), ('CCO APPROVED', 'CCO APPROVED'), ('BHM APPROVED', 'BHM APPROVED'), ('BHA APPROVED', 'BHA APPROVED'), ('MD APPROVED', 'MD APPROVED')], max_length=255),
        ),
        migrations.AlterField(
            model_name='caadapprovalhistory',
            name='user_action',
            field=models.CharField(choices=[('BHA Approval', 'BHA Approval'), ('BHM Approval', 'BHM Approval'), ('OC Approval', 'OC Approval'), ('RH Approval', 'RH Approval'), ('HCS Approval', 'HCS Approval'), ('CCO Approval', 'CCO Approval'), ('MD Approval', 'MD Approval')], max_length=255, null=True),
        ),
    ]
