# Generated by Django 3.2.9 on 2023-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caad', '0002_auto_20230325_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='caadheader',
            name='revert_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caadapprovalhistory',
            name='action_status',
            field=models.CharField(choices=[('RH APPROVED', 'RH APPROVED'), ('OC APPROVED', 'OC APPROVED'), ('HCS APPROVED', 'HCS APPROVED'), ('CCO APPROVED', 'CCO APPROVED'), ('BHM APPROVED', 'BHM APPROVED'), ('BHA APPROVED', 'BHA APPROVED'), ('MD APPROVED', 'MD APPROVED'), ('RH DECLINED', 'RH DECLINED'), ('OC DECLINED', 'OC DECLINED'), ('HCS DECLINED', 'HCS DECLINED'), ('CCO DECLINED', 'CCO DECLINED'), ('BHM DECLINED', 'BHM DECLINED'), ('BHA DECLINED', 'BHA DECLINED'), ('MD DECLINED', 'MD DECLINED')], max_length=255),
        ),
        migrations.AlterField(
            model_name='caadapprovalhistory',
            name='user_action',
            field=models.CharField(choices=[('BHA Approval', 'BHA Approval'), ('BHM Approval', 'BHM Approval'), ('OC Approval', 'OC Approval'), ('RH Approval', 'RH Approval'), ('HCS Approval', 'HCS Approval'), ('CCO Approval', 'CCO Approval'), ('MD Approval', 'MD Approval'), ('BHA Declined', 'BHA Declined'), ('BHM Declined', 'BHM Declined'), ('OC Declined', 'OC Declined'), ('RH Declined', 'RH Declined'), ('HCS Declined', 'HCS Declined'), ('CCO Declined', 'CCO Declined'), ('MD Declined', 'MD Declined')], max_length=255, null=True),
        ),
    ]
