# Generated by Django 3.2.9 on 2023-04-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caad', '0003_auto_20230325_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='caadapprovalusers',
            name='other_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
