# Generated by Django 3.2.9 on 2023-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caad', '0004_alter_caadapprovalusers_approver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caadapprovalusers',
            name='approver_email',
            field=models.CharField(max_length=255),
        ),
    ]
