# Generated by Django 3.2.9 on 2023-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caad', '0005_alter_caadapprovalusers_approver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='caadapprovalusers',
            name='other_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
