# Generated by Django 3.2.9 on 2023-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='address1',
            field=models.CharField(blank=True, db_column='Address_1', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='cms_created',
            field=models.BooleanField(blank=True, db_column='CMS_Created', default=False, null=True),
        ),
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='customer_created_by',
            field=models.CharField(blank=True, db_column='Customer_Created_By', default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='dss_name',
            field=models.CharField(blank=True, db_column='DSS_Name', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='dss_owner',
            field=models.CharField(blank=True, db_column='DSS_Owner', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='feeder_type',
            field=models.CharField(blank=True, db_column='FeederType', max_length=300, null=True),
        ),
    ]
