# Generated by Django 3.2.9 on 2023-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230312_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='firstname',
            field=models.CharField(blank=True, db_column='Firstname', default='', max_length=128, null=True),
        ),
    ]
