# Generated by Django 3.2.9 on 2023-03-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ecmicustomersnew_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=50, null=True),
        ),
    ]
