# Generated by Django 3.2.9 on 2023-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ecmicustomersnew_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecmicustomersnew',
            name='statuscode',
            field=models.CharField(blank=True, db_column='StatusCode', max_length=10, null=True),
        ),
    ]
