# Generated by Django 3.2.9 on 2023-03-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ecmicustomersnew_statuscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='customersk',
            field=models.IntegerField(blank=True, db_column='CustomerSK', null=True),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
