# Generated by Django 3.2.9 on 2023-03-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDrafts',
        ),
    ]
