# Generated by Django 3.2.9 on 2023-03-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0003_customerdrafts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdrafts',
            old_name='address1',
            new_name='address',
        ),
    ]
