# Generated by Django 3.2.9 on 2023-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0004_rename_address1_customerdrafts_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdrafts',
            name='address1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
