# Generated by Django 3.2.9 on 2023-03-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0005_customerdrafts_address1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerEditQueue',
        ),
    ]
