# Generated by Django 3.2.9 on 2023-03-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0006_delete_customereditqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEditQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('customer_id', models.IntegerField(default=0)),
                ('accountno', models.CharField(default='', max_length=255)),
                ('firstname', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('othernames', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('mobile', models.CharField(default='', max_length=255)),
                ('address1', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('statuscode', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('building_description', models.CharField(default='', max_length=255)),
                ('lga', models.CharField(default='', max_length=255)),
                ('premise_type', models.CharField(default='', max_length=255)),
                ('region', models.CharField(default='', max_length=255)),
                ('buid', models.CharField(default='', max_length=255)),
                ('servicecenter', models.CharField(default='', max_length=255)),
                ('customer_type', models.CharField(default='', max_length=255)),
                ('accounttype', models.CharField(default='', max_length=255)),
                ('business_type', models.CharField(default='', max_length=255)),
                ('landlord_name', models.CharField(default='', max_length=255)),
                ('landlord_phone', models.CharField(default='', max_length=255)),
                ('injection_sub_station', models.CharField(default='', max_length=255)),
                ('meter_oem', models.CharField(default='', max_length=255)),
                ('cin', models.CharField(default='', max_length=255)),
                ('service_band', models.CharField(default='', max_length=255)),
                ('upriser_id', models.CharField(default='', max_length=255)),
                ('dss_id', models.CharField(default='', max_length=255)),
                ('dss_name', models.CharField(default='', max_length=255)),
                ('dss_owner', models.CharField(default='', max_length=255)),
                ('feeder_type', models.CharField(default='', max_length=255)),
                ('feeder_name', models.CharField(default='', max_length=255)),
                ('feederid', models.CharField(default='', max_length=255)),
                ('ltpoleid', models.CharField(default='', max_length=255)),
                ('created_by', models.CharField(default='', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('edited_by', models.CharField(default='', max_length=255)),
                ('edited_date', models.DateField(auto_now=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(default='', max_length=255)),
                ('approved_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='', max_length=255)),
                ('comments', models.TextField(default='')),
                ('cms_created', models.BooleanField(default=False)),
                ('is_fresh', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('customer_created_by', models.CharField(default='', max_length=255)),
                ('bhm_aproved', models.BooleanField(default=False)),
                ('auditor_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer_editqueue',
            },
        ),
    ]
