# Generated by Django 3.2.9 on 2023-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0007_customereditqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customereditqueue',
            name='customer_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
