# Generated by Django 3.2.9 on 2023-03-25 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasksInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=255)),
                ('task_description', models.CharField(max_length=1000)),
                ('task_sentby', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created Date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created By')),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='Edited Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
