# Generated by Django 3.2.9 on 2023-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasksinbox',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='usertasksinbox',
            name='edited_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Edited Date'),
        ),
        migrations.AlterField(
            model_name='usertasksinbox',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
