# Generated by Django 3.2.9 on 2023-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_usertasksinbox_associated_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasksinbox',
            name='task_type',
            field=models.CharField(default='CAAD', max_length=50),
        ),
    ]
