# Generated by Django 3.2.9 on 2023-04-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcmiPaymentHistory',
            fields=[
                ('transref', models.CharField(max_length=360, primary_key=True, serialize=False)),
                ('enteredby', models.IntegerField(blank=True, null=True)),
                ('transdate', models.DateTimeField(blank=True, null=True)),
                ('transamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('transstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('meterno', models.CharField(blank=True, max_length=20, null=True)),
                ('transactionresponsemessage', models.TextField(blank=True, null=True)),
                ('paymenttype', models.IntegerField(blank=True, null=True)),
                ('units', models.DecimalField(blank=True, db_column='Units', decimal_places=2, max_digits=18, null=True)),
                ('costofunits', models.DecimalField(blank=True, db_column='CostOfUnits', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'ecmi_payment_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EcmiTransactions',
            fields=[
                ('transactionno', models.IntegerField(db_column='TransactionNo', primary_key=True, serialize=False)),
                ('cspclientid', models.CharField(blank=True, db_column='CSPClientID', max_length=10, null=True)),
                ('transactiondatetime', models.DateTimeField(blank=True, db_column='TransactionDateTime', null=True)),
                ('operatorid', models.CharField(blank=True, db_column='OperatorID', max_length=20, null=True)),
                ('meterno', models.CharField(blank=True, db_column='MeterNo', max_length=20, null=True)),
                ('accountno', models.CharField(blank=True, db_column='AccountNo', max_length=24, null=True)),
                ('transactiontype', models.IntegerField(blank=True, db_column='TransactionType', null=True)),
                ('units', models.DecimalField(blank=True, db_column='Units', decimal_places=2, max_digits=11, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=11, null=True)),
                ('fc', models.DecimalField(blank=True, db_column='FC', decimal_places=2, max_digits=11, null=True)),
                ('mmf', models.DecimalField(blank=True, db_column='MMF', decimal_places=2, max_digits=11, null=True)),
                ('kva', models.DecimalField(blank=True, db_column='KVA', decimal_places=2, max_digits=12, null=True)),
                ('vat', models.DecimalField(blank=True, db_column='VAT', decimal_places=2, max_digits=11, null=True)),
                ('token', models.CharField(blank=True, db_column='Token', max_length=20, null=True)),
                ('tokentype', models.IntegerField(blank=True, db_column='TokenType', null=True)),
                ('reasons', models.CharField(blank=True, db_column='Reasons', max_length=200, null=True)),
                ('transactioncomplete', models.BooleanField(blank=True, db_column='TransactionComplete', null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('status1', models.CharField(blank=True, max_length=1, null=True)),
                ('buid', models.CharField(blank=True, db_column='BUID', max_length=10, null=True)),
                ('transref', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('month', models.IntegerField(blank=True, db_column='Month', null=True)),
                ('day', models.IntegerField(blank=True, db_column='Day', null=True)),
            ],
            options={
                'db_table': 'ecmi_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmsPayments',
            fields=[
                ('rowguid', models.CharField(blank=True, max_length=36, null=True)),
                ('paymentid', models.CharField(db_column='PaymentID', max_length=360, primary_key=True, serialize=False)),
                ('billid', models.CharField(blank=True, db_column='BillID', max_length=36, null=True)),
                ('paymenttransactionid', models.CharField(blank=True, db_column='PaymentTransactionId', max_length=36, null=True)),
                ('receiptnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentsource', models.CharField(blank=True, db_column='PaymentSource', max_length=5, null=True)),
                ('meterno', models.CharField(blank=True, db_column='MeterNo', max_length=20, null=True)),
                ('accountno', models.CharField(blank=True, db_column='AccountNo', max_length=20, null=True)),
                ('paydate', models.DateTimeField(blank=True, db_column='PayDate', null=True)),
                ('paymonth', models.IntegerField(blank=True, db_column='PayMonth', null=True)),
                ('payyear', models.IntegerField(blank=True, db_column='PayYear', null=True)),
                ('operatorid', models.IntegerField(blank=True, db_column='OperatorID', null=True)),
                ('totaldue', models.DecimalField(blank=True, db_column='TotalDue', decimal_places=2, max_digits=18, null=True)),
                ('payments', models.DecimalField(blank=True, db_column='Payments', decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(blank=True, db_column='Balance', decimal_places=2, max_digits=18, null=True)),
                ('processed', models.BooleanField(blank=True, db_column='Processed', null=True)),
                ('processeddate', models.DateTimeField(blank=True, db_column='ProcessedDate', null=True)),
                ('businessunit', models.CharField(blank=True, db_column='BusinessUnit', max_length=10, null=True)),
                ('reconciled', models.BooleanField(blank=True, db_column='Reconciled', null=True)),
                ('reconciledby', models.IntegerField(blank=True, db_column='ReconciledBy', null=True)),
                ('reversedby', models.IntegerField(blank=True, db_column='ReversedBy', null=True)),
                ('batchuniqueid', models.CharField(blank=True, db_column='BatchUniqueID', max_length=36, null=True)),
                ('dateengtered', models.DateTimeField(blank=True, db_column='DateEngtered', null=True)),
                ('customerid', models.CharField(blank=True, db_column='CustomerID', max_length=36, null=True)),
            ],
            options={
                'db_table': 'ems_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmsPaymentTrans',
            fields=[
                ('transid', models.CharField(max_length=360, primary_key=True, serialize=False)),
                ('transref', models.CharField(blank=True, max_length=30, null=True)),
                ('enteredby', models.IntegerField(blank=True, null=True)),
                ('transdate', models.DateTimeField(blank=True, null=True)),
                ('transamount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('transstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('accountno', models.CharField(blank=True, max_length=20, null=True)),
                ('transactionresponsemessage', models.TextField(blank=True, null=True)),
                ('paymenttype', models.IntegerField(blank=True, null=True)),
                ('transactionbusinessunit', models.CharField(blank=True, db_column='TransactionBusinessUnit', max_length=10, null=True)),
                ('rowguid', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'ems_payment_trans',
                'managed': False,
            },
        ),
    ]
