# Generated by Django 3.2.9 on 2023-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_ecmitransactions_transref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecmitransactions',
            name='transref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
