# Generated by Django 3.2.9 on 2023-03-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaadHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('buid', models.CharField(max_length=255)),
                ('bucode', models.CharField(max_length=255)),
                ('total_accrued', models.FloatField()),
                ('vat', models.FloatField()),
                ('current_outstanding_bal', models.FloatField()),
                ('refund_amount', models.FloatField()),
                ('is_metered', models.BooleanField()),
                ('total_estimate', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('revert_comments', models.TextField(default='')),
                ('state', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('servicecenter', models.CharField(max_length=255)),
                ('percentage_approval', models.FloatField(default=0.0)),
                ('last_approval', models.CharField(default='', max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created Date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created By')),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='Edited Date')),
            ],
        ),
        migrations.CreateModel(
            name='CaadLineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('months', models.IntegerField()),
                ('tarrif', models.FloatField()),
                ('recom_unit', models.FloatField()),
                ('mab', models.FloatField()),
                ('ebm', models.FloatField()),
                ('error_flag', models.BooleanField(default=False)),
                ('index', models.CharField(default='', max_length=255)),
                ('uuid', models.CharField(default='', max_length=255)),
                ('present_reading', models.FloatField(default=0.0)),
                ('last_actual_reading', models.FloatField(default=0.0)),
                ('consumed', models.FloatField(default=0.0)),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='Edited Date')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='caad.caadheader')),
            ],
        ),
        migrations.CreateModel(
            name='CaadApprovalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_name', models.CharField(max_length=255)),
                ('approver_position', models.CharField(max_length=255)),
                ('approver_email', models.CharField(max_length=255)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=255)),
                ('caad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caad.caadheader')),
            ],
        ),
        migrations.CreateModel(
            name='CaadApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=255)),
                ('creator_role', models.CharField(max_length=255)),
                ('bhm_compliance', models.BooleanField(default=False)),
                ('operation_compliance', models.BooleanField(default=False)),
                ('completed_approval_sequence', models.BooleanField(default=False)),
                ('user_action', models.CharField(choices=[('BHM Approval', 'BHM Approval'), ('OC Approval', 'OC Approval'), ('RH Approval', 'RH Approval'), ('HCS Approval', 'HCS Approval'), ('CCO Approval', 'CCO Approval'), ('MD Approval', 'MD Approval')], max_length=255, null=True)),
                ('action_status', models.CharField(choices=[('RH APPROVED', 'RH APPROVED'), ('OC APPROVED', 'OC APPROVED'), ('HCS APPROVED', 'HCS APPROVED'), ('CCO APPROVED', 'CCO APPROVED'), ('BHM APPROVED', 'BHM APPROVED'), ('MD APPROVED', 'MD APPROVED')], max_length=255)),
                ('rejected_reason', models.CharField(default='', max_length=255)),
                ('percentage_approval', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created Date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created By')),
                ('edited_date', models.DateTimeField(blank=True, null=True, verbose_name='Edited Date')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caad.caadheader')),
            ],
        ),
    ]
