# Generated by Django 3.2.9 on 2023-03-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaadApprovalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_name', models.CharField(max_length=255)),
                ('approver_position', models.CharField(max_length=255)),
                ('approver_email', models.CharField(max_length=255)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=255)),
                ('caad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caad.caadheader')),
            ],
        ),
    ]
