# Generated by Django 3.2.9 on 2023-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20230412_1148'),
    ]

    operations = [
        
        
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='bookno',
            field=models.CharField(blank=True, db_column='BookNo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='buid',
            field=models.CharField(blank=True, db_column='BUID', max_length=100, null=True),
        ),
       
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='statuscode',
            field=models.CharField(blank=True, db_column='StatusCode', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='tariffcode',
            field=models.CharField(blank=True, db_column='TariffCode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='utid',
            field=models.CharField(blank=True, db_column='UTID', max_length=100, null=True),
        ),
    ]
