# Generated by Django 3.2.9 on 2023-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20230412_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcmiTariff',
            fields=[
                ('tariffid', models.DecimalField(blank=True, db_column='TariffID', decimal_places=0, max_digits=20, null=True)),
                ('tariffcode', models.CharField(blank=True, db_column='TariffCode', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('addeddate', models.DateTimeField(blank=True, db_column='AddedDate', null=True)),
                ('status1', models.CharField(blank=True, max_length=2, null=True)),
                ('oldtariffcode', models.CharField(blank=True, db_column='OldTariffCode', max_length=5, null=True)),
            ],
            options={
                'db_table': 'ecmi_tariff',
                'managed': True,
            },
        ),
        
        migrations.AddField(
            model_name='emscustomersnew',
            name='account_nos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='accountno',
            field=models.CharField(db_column='AccountNo', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecmicustomersnew',
            name='customer_created_by',
            field=models.CharField(blank=True, db_column='Customer_Created_By', default='', max_length=1000, null=True),
        ),
    ]
