# Generated by Django 3.2.9 on 2023-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20230510_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecmicustomersnew',
            name='id',
        ),
        migrations.AlterField(
            model_name='ecmitariff',
            name='tariffid',
            field=models.DecimalField(db_column='TariffID', decimal_places=0, max_digits=20, primary_key=True, serialize=False),
        ),
    ]
