# Generated by Django 3.2.9 on 2023-05-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20230510_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecmitariff',
            options={'managed': False},
        ),
    ]
