# Generated by Django 3.2.9 on 2023-05-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_ecmitariff_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmsTariff',
            fields=[
                ('tariffid', models.DecimalField(db_column='TariffID', decimal_places=0, default=0, max_digits=20, primary_key=True, serialize=False)),
                ('tariffcode', models.CharField(blank=True, db_column='TariffCode', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('accounttype', models.CharField(blank=True, db_column='AccountType', max_length=50, null=True)),
                ('addeddate', models.DateTimeField(blank=True, db_column='AddedDate', null=True)),
                ('storedaverage', models.IntegerField(blank=True, db_column='StoredAverage', null=True)),
                ('ismd', models.BooleanField(blank=True, db_column='isMD', null=True)),
                ('usageratio', models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True)),
                ('rowguid', models.CharField(blank=True, max_length=360, null=True)),
                ('newtariffcode', models.CharField(blank=True, db_column='NewTariffCode', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ems_tariff',
                'managed': False,
            },
        ),
    ]
