# Generated by Django 3.2.9 on 2023-03-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmservicecentre',
            options={'managed': True},
        ),
    ]
