# Generated by Django 3.2.9 on 2023-03-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_crmservicecentre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmservicecentre',
            name='service_center_address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
