# Generated by Django 3.2.9 on 2023-03-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_crmservicecentre_service_center_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmbusinesshub',
            options={'managed': True},
        ),
    ]
