# Generated by Django 3.2.9 on 2023-03-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_crmbusinesshub_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmbusinesshub',
            name='buid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
