# Generated by Django 3.2.9 on 2023-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_crmbusinesshub_buid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmbusinesshub',
            name='buid',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
