# Generated by Django 3.2.9 on 2023-03-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_crmbusinesshub_buid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmservicecentre',
            name='service_center_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
