# Generated by Django 3.2.9 on 2023-03-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_crmservicecentre_service_center_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmbusinesshub',
            name='buid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crmservicecentre',
            name='service_center_address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
