# Generated by Django 3.2.9 on 2023-03-28 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20230328_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmregion',
            options={'managed': True},
        ),
    ]
