# Generated by Django 3.2.9 on 2023-03-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_crmregion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmregion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
