ECMI_FIELDS = [
        "accountno",
        "bookno",
        "meterno",
        "tariffid",
        "oldaccountno",
        "surname",
        "othernames",
        "firstname",
        "address",
        "address1",
        "state",
        "mobile",
        "email",
        "arrearsbalance",
        "buid",
        "status",
        "accounttype",
        "tariffcode",
        "dss_id",
        'dss_owner',
        'dss_name',
        "servicecenter",
        'city',
        'statuscode',
        "kyc",
        "title",
        "gender",
        "building_description",
        "lga",
        "premise_type",
        "region",
        "customer_type",
        "business_type",
        "feeder_name",
        "service_band",
        "landlord_name",
        "landlord_phone",
        "tenant",
        "landlord",
        "injection_sub_station",
        "cin",
        "opendate",
        "utid",
        "transid",
        "operatorname",
        "activated",
        "lastmodifieddate",
        "operatormodified",
        "modifiedcount",
        
        "meteroem",
        "upriserid",
        "feederid",
        "feeder_type",
        "ltpoleid",
        "latitude",
        "longitude"
        ]


EMS_FIELDS = keys = [
    'accountno',
    'meterno',
    'surname',
    'firstname',
    'othernames',
    'address1',
    'address2',
    'city',
    'state',
    'email',
    'arrearsbalance',
    'applicationdate',
    'mobile',
    'accttypedesc',
    'giscoordinate',
    'guarantorname',
    'guarantoraddress',
    'upriserno',
    'buid',
    'statuscode',
    'accounttype',
    'newtariffcode',
    'dss_id',
    'servicecenter',
    
    
]

# 'kyc',
#     'title',
#     'gender',
#     'building_description',
#     'lga',
#     'premise_type',
#     'region',
#     'customer_type',
#     'accounttype',
#     'business_type',
#     'feeder_name',
#     'service_band',
#     'contactname',
#     'contactphone',
#     'contactemail',
#     'landlord_name',
#     'landlord_phone',
#     'tenant',
#     'landlord', 
#     'injection_sub_station', 
#     'cin', 
#     'meteroem', 
#     'upriserid', 
#     'feederid', 
#     'ltpoleid', 
#     'latitude', 
#     'longitude'