# Generated by Django 3.2.9 on 2023-03-10 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmBusinessHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('other_info', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crm_business_hub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrmRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('other_info', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crm_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrmServiceCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('business_hub', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('other_info', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crm_service_centre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('biz_hub', models.CharField(blank=True, max_length=250, null=True)),
                ('service_center', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=250, null=True)),
                ('rid', models.CharField(blank=True, max_length=250, null=True)),
                ('buid', models.CharField(blank=True, max_length=250, null=True)),
                ('scid', models.CharField(blank=True, max_length=250, null=True)),
                ('service_center_address', models.CharField(blank=True, max_length=250, null=True)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
