# Generated by Django 3.2.9 on 2023-03-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmsBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowguid', models.CharField(blank=True, max_length=36, null=True)),
                ('buid', models.CharField(blank=True, db_column='BUID', max_length=5, null=True)),
                ('zoneid', models.CharField(blank=True, db_column='ZoneID', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('contactperson', models.CharField(blank=True, db_column='ContactPerson', max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='EMail', max_length=50, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=50, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=10, null=True)),
                ('refcode', models.CharField(blank=True, max_length=5, null=True)),
                ('bucode', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'ems_business_unit',
                'managed': False,
            },
        ),
    ]
