# Generated by Django 3.2.9 on 2023-03-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0002_auto_20230320_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customereditqueue',
            options={'managed': True},
        ),
    ]
