# Generated by Django 3.2.9 on 2023-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0003_alter_customereditqueue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customereditqueue',
            name='adt_approver',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customereditqueue',
            name='bhm_approver',
            field=models.CharField(default='', max_length=255),
        ),
    ]
