# Generated by Django 3.2.9 on 2023-04-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0004_auto_20230323_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdrafts',
            options={'managed': True},
        ),
    ]
