# Generated by Django 3.2.9 on 2023-04-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0005_alter_customerdrafts_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdrafts',
            old_name='meter_oem',
            new_name='meteroem',
        ),
    ]
