# Generated by Django 3.2.9 on 2023-04-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0007_rename_meteroem_customerdrafts_meter_oem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdrafts',
            old_name='meter_oem',
            new_name='meteroem',
        ),
    ]
