# Generated by Django 3.2.9 on 2023-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsmanager', '0008_rename_meter_oem_customerdrafts_meteroem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customereditqueue',
            name='last_edited_fields',
            field=models.JSONField(default={'fields': []}),
        ),
    ]
