let userdata = [
    {
        "id": 80,
        "name": "Ibedc User",
        "login": "user@ibedc.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "RH",
        "enable_2fa": true,
        "manage_2fa": false,
        "can_create_customer": true,
        "can_approve_caad": true,
        "last_authentication": "2023-01-31 15:36:40",
    },
    {
        "id": 79,
        "name": "Managing Director",
        "login": "md@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "Access Rights",
        "region": "granted",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "hq",
        "can_approve": true,
        "position": "MD",
        "enable_2fa": false,
        "manage_2fa": true,
        "can_create_customer": true,
        "can_approve_caad": false,
        "last_authentication": "2023-01-07 08:40:03",
    },
    {
        "id": 78,
        "name": "Chief Commercial Officer",
        "login": "cco@gmail.com",
        "active": false,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "CCO",
        "enable_2fa": false,
        "manage_2fa": true,
        "can_create_customer": null,
        "can_approve_caad": null,
        "last_authentication": "2023-02-15 11:42:11",
    },
    {
        "id": 77,
        "name": "Head Customer Support",
        "login": "hcs@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "HCS",
        "enable_2fa": false,
        "manage_2fa": false,
        "can_create_customer": null,
        "can_approve_caad": null,
        "last_authentication": "2022-12-28 12:14:45",
    },
    {
        "id": 76,
        "name": "Regional Head",
        "login": "rh@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "RH",
        "enable_2fa": false,
        "manage_2fa": false,
        "can_create_customer": null,
        "can_approve_caad": null,
        "can_approve_caad": null,
        "last_authentication": "2023-12-28 12:14:45"
    },
    {
        "id": 80,
        "name": "Ibedc User",
        "login": "user@ibedc.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "RH",
        "enable_2fa": true,
        "manage_2fa": false,
        "can_create_customer": true,
        "can_approve_caad": true,
        "last_authentication": "2023-01-31 15:36:40",
    },
    {
        "id": 79,
        "name": "Managing Director",
        "login": "md@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "Access Rights",
        "region": "granted",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "hq",
        "can_approve": true,
        "position": "MD",
        "enable_2fa": false,
        "manage_2fa": true,
        "can_create_customer": true,
        "can_approve_caad": false,
        "last_authentication": "2023-01-07 08:40:03",
    },
    {
        "id": 78,
        "name": "Chief Commercial Officer",
        "login": "cco@gmail.com",
        "active": false,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "CCO",
        "enable_2fa": false,
        "manage_2fa": true,
        "can_create_customer": null,
        "can_approve_caad": null,
        "last_authentication": "2023-02-15 11:42:11",
    },
    {
        "id": 77,
        "name": "Head Customer Support",
        "login": "hcs@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "HCS",
        "enable_2fa": false,
        "manage_2fa": false,
        "can_create_customer": null,
        "can_approve_caad": null,
        "last_authentication": "2022-12-28 12:14:45",
    },
    {
        "id": 76,
        "name": "Regional Head",
        "login": "rh@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "RH",
        "enable_2fa": false,
        "manage_2fa": false,
        "can_create_customer": null,
        "can_approve_caad": null,
        "can_approve_caad": null,
        "last_authentication": "2023-12-28 12:14:45"
    },
    {
        "id": 80,
        "name": "Ibedc User",
        "login": "user@ibedc.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "RH",
        "enable_2fa": true,
        "manage_2fa": false,
        "can_create_customer": true,
        "can_approve_caad": true,
        "last_authentication": "2023-01-31 15:36:40",
    },
    {
        "id": 79,
        "name": "Managing Director",
        "login": "md@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "Access Rights",
        "region": "granted",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "hq",
        "can_approve": true,
        "position": "MD",
        "enable_2fa": false,
        "manage_2fa": true,
        "can_create_customer": true,
        "can_approve_caad": false,
        "last_authentication": "2023-01-07 08:40:03",
    },
    {
        "id": 78,
        "name": "Chief Commercial Officer",
        "login": "cco@gmail.com",
        "active": false,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "CCO",
        "enable_2fa": false,
        "manage_2fa": true,
        "can_create_customer": null,
        "can_approve_caad": null,
        "last_authentication": "2023-02-15 11:42:11",
    },
    {
        "id": 77,
        "name": "Head Customer Support",
        "login": "hcs@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "HCS",
        "enable_2fa": false,
        "manage_2fa": false,
        "can_create_customer": null,
        "can_approve_caad": null,
        "last_authentication": "2022-12-28 12:14:45",
    },
    {
        "id": 76,
        "name": "Regional Head",
        "login": "rh@gmail.com",
        "active": true,
        "suspend_user": "active",
        "permission": "None",
        "region": "Oyo",
        "business_unit": "granted",
        "servicecenter": "granted",
        "permission_hierarchy": "regions",
        "can_approve": true,
        "position": "RH",
        "enable_2fa": false,
        "manage_2fa": false,
        "can_create_customer": null,
        "can_approve_caad": null,
        "can_approve_caad": null,
        "last_authentication": "2023-12-28 12:14:45"
    }
]

exports.userdata = userdata