# Generated by Django 3.2.9 on 2023-03-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, verbose_name='Table Name')),
                ('record_id', models.IntegerField(verbose_name='Record ID')),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created By')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
                ('updated_by', models.CharField(max_length=255, verbose_name='Updated By')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Audits log',
            },
        ),
    ]
